server:
  port: 8080
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    # 连接容器中的mysql,并建一个数据库test, 用于连接测试
    url: jdbc:mysql://172.17.0.2:3306/test?characterEncoding=utf-8&serverTimezone=GMT%2B8&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  redis:
    database: 1
    host: 172.17.0.3
    port: 6379
    password: 123456
    pool:
      max-active: 1000
      max-wait: -1
      min-idle: 2
      max-idle: 10
    timeout: 0